.pragma library

var STRINGS = ({
    "sidebar_sessions": "会话",
    "sidebar_library_title": "工作区",
    "sidebar_memory": "记忆",
    "sidebar_control_tower": "指挥舱",
    "sidebar_skills": "技能",
    "sidebar_tools_nav": "工具",
    "sidebar_cron": "自动任务",
    "sidebar_empty_title": "开始一个新对话",
    "sidebar_empty_hint": "点击即可新建会话",
    "sidebar_empty_cta": "新建对话",
    "sidebar_loading_title": "正在加载会话",
    "sidebar_loading_hint": "稍等一下，历史会话马上出现",
    "sidebar_session_lookup_placeholder": "搜索会话或输入 session ref…",
    "sidebar_session_lookup_placeholder_compact": "搜索会话…",
    "sidebar_session_default_label": "默认",
    "sidebar_session_recent_label": "最近",
    "sidebar_session_resolved_label": "解析",
    "chat_empty_title": "开始对话",
    "chat_empty_hint": "在下面输入消息",
    "chat_hub": "中枢",
    "hub_starting": "启动中…",
    "hub_running": "运行中",
    "hub_error": "错误",
    "hub_channels_idle": "将启动的渠道",
    "hub_channels_running": "活跃渠道",
    "hub_channels_error": "异常渠道",
    "button_start_hub": "启动中枢",
    "profile_switch": "分身档案",
    "profile_count_badge": "%1 个分身",
    "profile_empty_title": "还没有分身",
    "profile_empty_hint": "先创建一个分身，再切换不同的人设、记忆和会话视图。",
    "profile_create_placeholder": "例如：工作搭子 / 深度研究员 / 生活管家",
    "profile_display_name_placeholder": "例如：研发档 / 日常 / 深度研究",
    "profile_delete_title": "确认删除这个分身？",
    "profile_delete_hint": "删除后，“%1”专属的人设提示词、记忆和会话历史都会被永久移除，之后无法恢复。",
    "profile_delete_irreversible": "不可撤销",
    "profile_delete_confirm": "确认删除",
    "profile_delete_cancel": "取消",
    "chat_placeholder": "给 Bao 发消息…",
    "chat_attach_title": "选择附件",
    "chat_loading_history": "加载会话中…",
    "section_app": "应用",
    "section_updates": "桌面更新",
    "section_agent_defaults": "回复方式与模型",
    "section_provider": "LLM 提供商",
    "section_channels": "渠道",
    "section_tools": "工具",
    "section_hub": "中枢",
    "section_provider_add": "添加 LLM 提供商",
    "section_provider_remove": "删除",
    "ui_language": "界面语言",
    "ui_language_auto": "自动（跟随系统）",
    "ui_language_zh": "中文",
    "ui_language_en": "English",
    "ui_theme": "界面主题",
    "ui_theme_system": "自动（跟随系统）",
    "ui_theme_light": "浅色",
    "ui_theme_dark": "深色",
    "update_auto_check": "自动更新",
    "update_status_up_to_date": "当前已是最新版本",
    "update_status_error": "更新失败",
    "update_action_check": "检查",
    "update_action_checking": "检查中",
    "update_action_install": "立即更新",
    "update_current_version": "当前版本",
    "update_latest_version": "最新版本",
    "update_modal_title": "发现新版本",
    "update_modal_later": "稍后",
    "update_modal_install": "更新",
    "settings_save": "保存",
    "settings_saved_hint": "已保存 — 重启中枢以应用",
    "settings_save_failed": "保存失败",
    "empty_setup_title": "欢迎使用 Bao",
    "empty_setup_hint": "请先在设置中配置 Provider 和模型（点击左下角 logo 进入设置）",
    "empty_starting_hint": "正在连接…",
    "empty_error_hint": "中枢启动失败",
    "empty_error_btn": "重试",
    "empty_chat_title": "准备就绪",
    "empty_chat_hint": "在下方输入消息开始对话",
    "empty_chat_idle_hint": "启动中枢后即可在这里继续对话",
    "empty_idle_title": "中枢未启动",
    "empty_idle_hint": "点击左侧中枢胶囊启动中枢",
    "session_delete_ok": "会话已删除",
    "session_delete_fail": "删除失败",
    "channel_desktop": "桌面",
    "channel_subagent": "子代理",
    "channel_system": "系统",
    "channel_heartbeat": "心跳",
    "channel_cron": "定时任务",
    "channel_telegram": "Telegram",
    "channel_discord": "Discord",
    "channel_whatsapp": "WhatsApp",
    "channel_feishu": "飞书",
    "channel_slack": "Slack",
    "channel_email": "邮件",
    "channel_qq": "QQ",
    "channel_dingtalk": "钉钉",
    "channel_imessage": "iMessage",
    "channel_other": "其他",
    "bubble_0": "点这里看设置",
    "bubble_1": "需要时再叫我",
    "bubble_2": "配置都在这里",
    "bubble_3": "先从这里开始",
    "bubble_4": "我准备好了",
    "sidebar_diagnostics": "日志",
    "sidebar_diagnostics_hint": "诊断",
    "copied_ok": "已复制",
    "child_session_read_only": "子代理线程为只读视图，请回到主对话继续追加提示。",
    "child_session_from_parent": "来源主会话",
    "child_session_running": "运行中",
    "child_session_failed": "失败",
    "child_session_completed": "已完成",
    "child_session_cancelled": "已取消",
    "parent_active_children": "当前子代理",
    "parent_linked_children": "已链接子代理",
    "parent_open_child_session": "打开子线程",
    "diagnostics_title": "运行诊断与日志",
    "diagnostics_close": "关闭",
    "diagnostics_empty_events": "当前没有结构化诊断事件。",
    "diagnostics_empty_logs": "当前还没有日志输出。",
    "diagnostics_recent_events": "最近诊断",
    "diagnostics_log_tail": "日志尾部",
    "diagnostics_log_file": "日志文件",
    "diagnostics_refresh": "刷新",
    "diagnostics_open_folder": "打开目录",
    "diagnostics_copy_tail": "复制尾部",
    "diagnostics_ask_bao": "发给 Bao",
    "diagnostics_sent": "诊断已发送",
    "diagnostics_hub_title": "中枢状态",
    "diagnostics_hub_idle": "还没启动",
    "diagnostics_hub_starting": "正在启动",
    "diagnostics_hub_running": "运行正常",
    "diagnostics_hub_error": "启动异常",
    "diagnostics_metrics_title": "运行观测",
    "workspace_memory_title": "记忆档案",
    "workspace_memory_caption": "这里将承载 Bao 的长期记忆浏览、筛选与管理。",
    "workspace_control_tower_title": "指挥舱",
    "workspace_control_tower_caption": "统一查看分身回复、自动化与待处理事项。",
    "workspace_skills_title": "技能",
    "workspace_skills_caption": "管理 AI 可用技能。",
    "workspace_tools_title": "工具",
    "workspace_tools_caption": "管理 AI 可用工具。",
    "workspace_cron_title": "自动任务",
    "workspace_cron_caption": "统一管理任务与自动检查。",
    "workspace_kicker_future": "即将到来"
})

function data() {
    return STRINGS
}
