.pragma library

var STRINGS = ({
    "sidebar_sessions": "Sessions",
    "sidebar_library_title": "Workspace",
    "sidebar_memory": "Memory",
    "sidebar_control_tower": "Control Tower",
    "sidebar_skills": "Skills",
    "sidebar_tools_nav": "Tools",
    "sidebar_cron": "Automation",
    "sidebar_empty_title": "Start a new chat",
    "sidebar_empty_hint": "Click to create one",
    "sidebar_empty_cta": "New chat",
    "sidebar_loading_title": "Loading sessions",
    "sidebar_loading_hint": "Your recent conversations will appear in a moment",
    "sidebar_session_lookup_placeholder": "Search sessions or enter a session ref…",
    "sidebar_session_lookup_placeholder_compact": "Search or ref…",
    "sidebar_session_default_label": "Default",
    "sidebar_session_recent_label": "Recent",
    "sidebar_session_resolved_label": "Resolved",
    "chat_empty_title": "Start a conversation",
    "chat_empty_hint": "Type a message below",
    "chat_hub": "Hub",
    "hub_starting": "Starting\u2026",
    "hub_running": "Running",
    "hub_error": "Error",
    "hub_channels_idle": "Channels to start",
    "hub_channels_running": "Active channels",
    "hub_channels_error": "Channel issues",
    "button_start_hub": "Start Hub",
    "profile_switch": "Profiles",
    "profile_count_badge": "%1 profiles",
    "profile_empty_title": "No profiles yet",
    "profile_empty_hint": "Create one first, then switch between different personas, memory, and chat views.",
    "profile_create_placeholder": "Examples: Work partner / Research mode / Life coach",
    "profile_display_name_placeholder": "Examples: Research / Daily / Deep Work",
    "profile_delete_title": "Delete this profile?",
    "profile_delete_hint": "This permanently removes the persona prompts, memory, and chat history stored under \"%1\". This cannot be undone.",
    "profile_delete_irreversible": "Permanent",
    "profile_delete_confirm": "Delete profile",
    "profile_delete_cancel": "Cancel",
    "chat_placeholder": "Message Bao\u2026",
    "chat_attach_title": "Choose Attachments",
    "chat_loading_history": "Loading session\u2026",
    "section_app": "App",
    "section_updates": "Desktop Updates",
    "section_agent_defaults": "Response Setup",
    "section_provider": "LLM Provider",
    "section_channels": "Channels",
    "section_tools": "Tools",
    "section_hub": "Hub",
    "section_provider_add": "Add LLM Provider",
    "section_provider_remove": "Remove",
    "ui_language": "UI Language",
    "ui_language_auto": "Auto (System)",
    "ui_language_zh": "Chinese",
    "ui_language_en": "English",
    "ui_theme": "Theme",
    "ui_theme_system": "Auto (System)",
    "ui_theme_light": "Light",
    "ui_theme_dark": "Dark",
    "update_auto_check": "Auto Update",
    "update_status_up_to_date": "You're on the latest version",
    "update_status_error": "Update failed",
    "update_action_check": "Check",
    "update_action_checking": "Checking",
    "update_action_install": "Install Now",
    "update_current_version": "Current",
    "update_latest_version": "Latest",
    "update_modal_title": "Update Available",
    "update_modal_later": "Later",
    "update_modal_install": "Install",
    "settings_save": "Save",
    "settings_saved_hint": "Saved \u2014 restart hub to apply",
    "settings_save_failed": "Save failed",
    "empty_setup_title": "Welcome to Bao",
    "empty_setup_hint": "Configure a Provider and Model in Settings first (click the logo in the bottom-left to open settings)",
    "empty_starting_hint": "Connecting\u2026",
    "empty_error_hint": "Hub failed to start",
    "empty_error_btn": "Retry",
    "empty_chat_title": "Ready to go",
    "empty_chat_hint": "Type a message below to start chatting",
    "empty_chat_idle_hint": "Start the hub to continue chatting here",
    "empty_idle_title": "Hub not started",
    "empty_idle_hint": "Click the hub capsule in the sidebar to start",
    "session_delete_ok": "Session deleted",
    "session_delete_fail": "Delete failed",
    "channel_desktop": "Desktop",
    "channel_subagent": "Subagent",
    "channel_system": "System",
    "channel_heartbeat": "Heartbeat",
    "channel_cron": "Cron",
    "channel_telegram": "Telegram",
    "channel_discord": "Discord",
    "channel_whatsapp": "WhatsApp",
    "channel_feishu": "Feishu",
    "channel_slack": "Slack",
    "channel_email": "Email",
    "channel_qq": "QQ",
    "channel_dingtalk": "DingTalk",
    "channel_imessage": "iMessage",
    "channel_other": "Other",
    "bubble_0": "Open settings here",
    "bubble_1": "Ready when you are",
    "bubble_2": "Configuration lives here",
    "bubble_3": "Start here first",
    "bubble_4": "I'm ready",
    "sidebar_diagnostics": "Logs",
    "sidebar_diagnostics_hint": "Inspect",
    "copied_ok": "Copied",
    "child_session_read_only": "This subagent thread is read-only. Continue from the parent conversation.",
    "child_session_from_parent": "Spawned from",
    "child_session_running": "Running",
    "child_session_failed": "Failed",
    "child_session_completed": "Completed",
    "child_session_cancelled": "Cancelled",
    "parent_active_children": "Active subagents",
    "parent_linked_children": "Linked subagents",
    "parent_open_child_session": "Open child thread",
    "diagnostics_title": "Runtime Diagnostics & Logs",
    "diagnostics_close": "Close",
    "diagnostics_empty_events": "No structured runtime diagnostics yet.",
    "diagnostics_empty_logs": "No log output has been captured yet.",
    "diagnostics_recent_events": "Recent diagnostics",
    "diagnostics_log_tail": "Log tail",
    "diagnostics_log_file": "Log file",
    "diagnostics_refresh": "Refresh",
    "diagnostics_open_folder": "Open Folder",
    "diagnostics_copy_tail": "Copy Tail",
    "diagnostics_ask_bao": "Ask Bao",
    "diagnostics_sent": "Diagnostics sent",
    "diagnostics_hub_title": "Hub State",
    "diagnostics_hub_idle": "Not started",
    "diagnostics_hub_starting": "Starting",
    "diagnostics_hub_running": "Running normally",
    "diagnostics_hub_error": "Startup issue",
    "workspace_memory_title": "Memory Archive",
    "workspace_memory_caption": "This area will host Bao's long-term memory browsing, filters, and editing flow.",
    "workspace_control_tower_title": "Control Tower",
    "workspace_control_tower_caption": "Monitor replies, automation, and review items across profiles.",
    "workspace_skills_title": "Skills",
    "workspace_skills_caption": "Manage AI available skills.",
    "workspace_tools_title": "Tools",
    "workspace_tools_caption": "Manage AI available tools.",
    "workspace_cron_title": "Automation",
    "workspace_cron_caption": "Manage tasks and automated checks.",
    "workspace_kicker_future": "Coming next"
})

function data() {
    return STRINGS
}
