function providerSections(root) {
    return [
        {
            "title": root.tr("先完成这 3 项", "Start with these 3 items"),
            "body": root.tr(
                "1. 先选一个模型服务预设。\n2. 大多数服务保持 openai；只有直连 Claude 或 Gemini 官方时再改。\n3. 填好 API 密钥，再到下一步选默认聊天模型。",
                "1. Start with one AI service preset.\n2. Keep openai for most services; only switch when using the official Claude or Gemini endpoints.\n3. Enter the API key, then move to the next step and choose the default chat AI."
            )
        },
        {
            "title": root.tr("每个字段是什么意思", "What each field means"),
            "body": root.tr(
                "名称：你自己起的别名，只是给配置里区分用途。\n类型：决定 Bao 用哪套协议接入。大多数第三方都选 openai。\nAPI 密钥：平台发给你的密钥，通常在 API Keys 页面生成。\nAPI 地址：官方或代理的基础地址；用官方默认就留空。",
                "Name: your local alias in the config.\nType: selects the SDK protocol Bao should use. Most third-party services use openai.\nAPI Key: the secret generated by the platform, usually from an API Keys page.\nAPI Base URL: the official or proxy base endpoint; leave empty for the official default."
            )
        },
        {
            "title": root.tr("常见提供商怎么获取密钥", "Where to get common provider keys"),
            "body": root.tr(
                "OpenAI：去 platform.openai.com → API Keys。\nAnthropic：去 console.anthropic.com → API Keys。\nGemini：去 aistudio.google.com → Get API key。\nOpenRouter：去 openrouter.ai/keys。\n如果你用硅基流动、DeepSeek、Groq、火山、DashScope、Moonshot、LM Studio、Ollama 之类，通常都按 openai 类型填写，并把它们提供的接口地址填到 API 地址。",
                "OpenAI: platform.openai.com → API Keys.\nAnthropic: console.anthropic.com → API Keys.\nGemini: aistudio.google.com → Get API key.\nOpenRouter: openrouter.ai/keys.\nFor SiliconFlow, DeepSeek, Groq, Volcengine, DashScope, Moonshot, LM Studio, Ollama, and similar services, keep the type as openai and put their endpoint into API Base URL."
            )
        },
        {
            "title": root.tr("模型名怎么填", "How to fill model names"),
            "body": root.tr(
                "默认聊天模型在 onboarding 第 3 步里选。最简单的方式是先点推荐卡片；如果你走代理平台，再按那个平台要求的模型名手动填写。",
                "The default chat AI is chosen in onboarding step 3. The easiest path is using one of the recommended cards first; when you use a proxy or aggregator, manually enter the exact model name required by that service."
            )
        }
    ]
}

function channelSections(root) {
    return [
        {
            "title": root.tr("怎么启用一个渠道", "How to enable a channel"),
            "body": root.tr(
                "先展开你要接入的渠道，填完必需字段，再打开开关并点击本卡保存。保存后重启网关生效。\n如果只是想先聊天，不需要立刻配所有渠道。新用户通常先配 Provider + 主模型就够了。",
                "Expand one channel, fill the required fields, then turn it on and save that section. Restart the hub after saving.\nIf you only want to start chatting, you do not need every channel right away. New users usually only need a provider plus a primary model."
            )
        },
        {
            "title": "Telegram / Discord / Slack",
            "body": root.tr(
                "Telegram：去 @BotFather 创建机器人，拿到机器人 Token。\nDiscord：去 Discord Developer Portal 创建应用和 Bot，开启 Message Content Intent，拿到机器人 Token。\nSlack：去 api.slack.com 创建应用，拿到机器人 Token 和应用 Token。",
                "Telegram: create a bot in @BotFather and copy the Bot Token.\nDiscord: create an app and bot in the Discord Developer Portal, enable Message Content Intent, then copy the Bot Token.\nSlack: create an app at api.slack.com, then copy the Bot Token and App Token."
            )
        },
        {
            "title": root.tr("其它渠道", "Other channels"),
            "body": root.tr(
                "WhatsApp / 飞书 / QQ / 钉钉 / Email / iMessage / Mochat 都只需要按字段提示填写。看不懂的项可以先留空，先把最基本的 token、地址或账号配好。",
                "WhatsApp, Feishu, QQ, DingTalk, Email, iMessage, and Mochat only need the fields shown in each card. If a field is unclear, leave it empty first and focus on the essential token, URL, or account details."
            )
        }
    ]
}

function agentSections(root) {
    return [
        {
            "title": root.tr("最少要填什么", "What is required"),
            "body": root.tr(
                "真正开始聊天时，至少需要一个默认聊天模型。后台模型、切换模型列表和高级选项都不是必填。",
                "To start chatting, you only need one default chat model. The background model, switchable model list, and advanced options are optional."
            )
        },
        {
            "title": root.tr("后台模型的作用", "What the background model does"),
            "body": root.tr(
                "它只用于标题生成、经验整理、摘要等后台小任务。留空没问题；只有你想把这些小任务换成更便宜的模型时才需要填。",
                "It is only used for background tasks such as title generation, experience cleanup, and summaries. Leaving it empty is fine; only fill it when you want those tasks to use a cheaper model."
            )
        },
        {
            "title": root.tr("什么时候再动高级选项", "When to touch advanced options"),
            "body": root.tr(
                "先让 Bao 聊起来，再按实际体验微调回复上限、长对话管理、推理强度和 service tier。除非你明确知道自己在调什么，否则保持默认最稳。",
                "Start chatting first, then adjust the reply limit, long-chat handling, reasoning depth, and service tier based on actual usage. The defaults are the safest path unless you know exactly what you are tuning."
            )
        }
    ]
}
